FROM rust:1.40-buster

# required by bingen
RUN apt-get update && \
	apt-get install -y \
		build-essential \
		cmake \
		clang \
		libclang-dev \
		llvm-dev \
		gcc-arm-linux-gnueabihf \
		g++-arm-linux-gnueabihf \
		git && \
	apt-get clean

RUN rustup target add armv7-unknown-linux-gnueabihf

RUN echo '[target.armv7-unknown-linux-gnueabihf]\n\
linker = "arm-linux-gnueabihf-gcc"\n'\
>> /usr/local/cargo/config

RUN mkdir -p /hal/native && \
	cd /hal/native && \
	git clone https://github.com/Lora-net/lora_gateway.git -b v5.0.1 && \
	git clone https://github.com/Lora-net/sx1302_hal.git -b V1.0.4

RUN cd /hal/native/lora_gateway && \
	make && \
	ln -s /hal/native/lora_gateway/libloragw/inc /usr/include/libloragw-sx1301 && \
	ln -s /hal/native/lora_gateway/libloragw/libloragw.a /usr/lib/libloragw-sx1301.a

RUN cd /hal/native/sx1302_hal && \
	make && \
	ln -s /hal/native/sx1302_hal/libloragw/inc /usr/include/libloragw-sx1302 && \
	ln -s /hal/native/sx1302_hal/libloragw/libloragw.a /usr/lib/libloragw-sx1302.a && \
	cp /hal/native/sx1302_hal/libtools/inc/* /usr/include && \
	cp /hal/native/sx1302_hal/libtools/*.a /usr/lib

RUN mkdir -p /hal/arm && \
	cd /hal/arm && \
	git clone https://github.com/Lora-net/lora_gateway.git -b v5.0.1 && \
	git clone https://github.com/Lora-net/sx1302_hal.git -b V1.0.4

# Needed for RAK shields, works with other shields too
RUN sed -i 's/define SPI_SPEED.*/define SPI_SPEED 2000000/g' /hal/arm/lora_gateway/libloragw/src/loragw_spi.native.c

RUN cd /hal/arm/lora_gateway && \
	ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make && \
	ln -s /hal/arm/lora_gateway/libloragw/inc /usr/arm-linux-gnueabihf/include/libloragw-sx1301 && \
	ln -s /hal/arm/lora_gateway/libloragw/libloragw.a /usr/arm-linux-gnueabihf/lib/libloragw-sx1301.a

RUN cd /hal/arm/sx1302_hal && \
	ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make && \
	ln -s /hal/arm/sx1302_hal/libloragw/inc /usr/arm-linux-gnueabihf/include/libloragw-sx1302 && \
	ln -s /hal/arm/sx1302_hal/libloragw/libloragw.a /usr/arm-linux-gnueabihf/lib/libloragw-sx1302.a && \
	cp /hal/arm/sx1302_hal/libtools/inc/* /usr/arm-linux-gnueabihf/include && \
	cp /hal/arm/sx1302_hal/libtools/*.a /usr/arm-linux-gnueabihf/lib

ENV PROJECT_PATH=/chirpstack-concentratord
RUN mkdir -p $PROJECT_PATH
WORKDIR $PROJECT_PATH
