#!/usr/bin/env bash

# Set config-file permissions
chown -R chirpstack:chirpstack /etc/chirpstack-concentratord-2g4
chmod 750 /etc/chirpstack-concentratord-2g4
chmod 640 /etc/chirpstack-concentratord-2g4/*.toml

#DEBHELPER#
