#!/usr/bin/env bash

# Set config-file permissions
chown -R chirpstack:chirpstack /etc/chirpstack-concentratord
chmod 750 /etc/chirpstack-concentratord
chmod 640 /etc/chirpstack-concentratord/*.toml

#DEBHELPER#
