#!/usr/bin/env bash

# Set config-file permissions
chown -R chirpstack:chirpstack /etc/chirpstack-concentratord-sx1301
chmod 750 /etc/chirpstack-concentratord-sx1301
chmod 640 /etc/chirpstack-concentratord-sx1301/*.toml

#DEBHELPER#
